version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: 'unless-stopped'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drone_feeder
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
      - ./init-mysql.sql:/data/application/init.sql

volumes:
  db:
